version: 0.2

env:
  variables:
    ENVIRONMENT: "prod1"
    TF_VERSION: "0.11.14"
  parameter-store:
    TF_VAR_github_oauth_token: "/easyarmediaserver/prod1/github_oauth_token"
    TF_VAR_cloudfront_secret_header: "/easyarmediaserver/prod1/cloudfront_secret_header"
    
phases:
  install:
    commands:
      # Terraform
    - "curl -s -qL -o terraform.zip https://releases.hashicorp.com/terraform/${TF_VERSION}/terraform_${TF_VERSION}_linux_amd64.zip"
    - "unzip -o terraform.zip -d /usr/bin"
    - rm -f terraform.zip

  build:
    commands:
      # Terraform infra
      - cd "$CODEBUILD_SRC_DIR/terraform"
      - terraform init
      - terraform workspace select $ENVIRONMENT
      - terraform plan -var-file=variables.$ENVIRONMENT.tfvars -out=terraform.plan -no-color
      - terraform apply ./terraform.plan -no-color
      - rm terraform.plan
      # S3
      - cd "$CODEBUILD_SRC_DIR"
      - mkdir dist
      - docker build . -t easyar-media-admin
      - docker run -v `pwd`/dist:/admin/dist easyar-media-admin yarn build:$ENVIRONMENT
      - cd dist && aws s3 sync . s3://easyar-$ENVIRONMENT-media-admin --delete